[tox]
envlist =
    py38-sa14-psycopg2
    py38-sa20-psycopg2
    py39-sa14-psycopg2
    py39-sa20-psycopg2
    py310-sa14-psycopg2
    py310-sa20-psycopg2
    py311-sa14-psycopg2
    py311-sa20-psycopg2
    py312-sa14-psycopg2
    py312-sa20-psycopg2
    py38-sa14-redshift_connector
    py38-sa20-redshift_connector
    py39-sa14-redshift_connector
    py39-sa20-redshift_connector
    py310-sa14-redshift_connector
    py310-sa20-redshift_connector
    py311-sa14-redshift_connector
    py311-sa20-redshift_connector
    py312-sa14-redshift_connector
    py312-sa20-redshift_connector
    lint
    docs

[testenv]
commands = 
    psycopg2: pytest {posargs} --dbdriver psycopg2
    redshift_connector: pytest {posargs} --dbdriver redshift_connector
passenv = PGPASSWORD,REDSHIFT_USERNAME,REDSHIFT_HOST,REDSHIFT_PORT,REDSHIFT_DATABASE,REDSHIFT_IAM_ROLE_ARN,AWS_ACCOUNT_ID,REDSHIFT_IAM_ROLE_NAME
deps =
    sa14: sqlalchemy>=1.4.48,<2.0
    sa20: sqlalchemy>=2.0.0,<3.0
    psycopg2: psycopg2>=2.8.6
    redshift_connector: redshift_connector>=2.0.907
    setuptools>=40.8.0
    alembic>=1.12.0
    packaging>=20.4
    psycopg2cffi>=2.8.1
    pytest>=7.2.1
    requests>=2.25.0

[testenv:lint]
deps =
    flake8==4.0.1
    psycopg2
    redshift_connector
commands=flake8 sqlalchemy_redshift tests

[testenv:docs]
changedir=docs
deps=
    -rrequirements-docs.txt
commands=
    sphinx-build -b html -d {envtmpdir}/doctrees . {envtmpdir}/html

[pytest]
addopts = --doctest-modules --doctest-glob='*.rst' --ignore=setup.py --ignore=docs/conf.py
doctest_optionflags = NORMALIZE_WHITESPACE
